version: '3.1'

# This is for local dev.

services:
  website:
    build: ./website
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn ross_website.wsgi -b 0.0.0.0:8000"
    #command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: MRD
    volumes:
      - ./website:/website
    ports:
      - "8000:8000"
    depends_on:
      - db 
    environment:
      - DEBUG=True
      - DB_USER=postgres
      - DB_PASS=password
      - DB_PORT=5432
      - SECRET_KEY=key
      - ALLOWED_HOSTS=*|
      - SQL_HOST=db
      - DATABASE=postgres
      - DBENGINE=django.db.backends.postgresql_psycopg2
      - BOKEH_URL=http://0.0.0.0:5001

  db:
    # image: postgres:10.1-alpine 
    # https://docs.docker.com/storage/volumes/   
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # Order here matters DB, USER, PASS
      #- POSTGRES_DB=madresearchden_db
      # name has to be postgres.
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  bokeh_server:
    build: ./test_bokeh_app
    # list two apps as show ./app1 ./app2
    command: bokeh serve --show ./bokeh_app/test_other_name.py  my_app.py --port 5001 --allow-websocket-origin=*
    container_name: bokeh_server_MRD
    volumes:
      - ./test_bokeh_app:/test_bokeh_app
    ports:
      - "5001:5001"
    depends_on:
      - website

volumes:
  postgres_data:
      # Why does this need to be here empty?


