version: '3'

services:
  website:
    build: ./website
    image: 729544618873.dkr.ecr.eu-west-2.amazonaws.com/madresearchden_test
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: MRD
    volumes:
      - ./website:/website
    ports:
      - "8000:8000"

  bokeh_server:
    build: ./test_bokeh_app
    image:
    command: bokeh serve --show ./my_app.py --port 5001 --allow-websocket-origin=0.0.0.0:8000
    container_name: bokeh_server_MRD
    volumes:
      - ./test_bokeh_app:/test_bokeh_app
    ports:
      - "5001:5001"
    depends_on:
      - website
