version: '3'

# This is for local dev.

services:
  website:
    build: ./website
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: MRD
    volumes:
      - ./website:/website
    ports:
      - "8000:8000"

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

# # Postgres
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

  bokeh_server:
    build: ./test_bokeh_app
    command: bokeh serve --show ./my_app.py --port 5001 --allow-websocket-origin=0.0.0.0:8000
    container_name: bokeh_server_MRD
    volumes:
      - ./test_bokeh_app:/test_bokeh_app
    ports:
      - "5001:5001"
    depends_on:
      - website

volumes:
  postgres_data:
      # Why does this need to be here empty?
