version: '3'

services:
  website:
    #image: ./website
    image: 729544618873.dkr.ecr.eu-west-2.amazonaws.com/madresearchden_test:latest
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: MRD
    # volumes:
    #   - ./website:/website
    ports:
      - "8000:8000"
    
    # Aws logging
    logging:
      driver: awslogs
      options: 
        awslogs-group: madresearchden-test
        awslogs-region: eu-west-2
        awslogs-stream-prefix: website
  # bokeh_server:
  #   image: ./test_bokeh_app
  #   command: bokeh serve --show ./bokeh_app --port 5001 --allow-websocket-origin=0.0.0.0:8000
  #   container_name: bokeh_server_MRD
  #   volumes:
  #     - ./test_bokeh_app:/test_bokeh_app
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - website
    
  #     # Aws logging
  #   logging:
  #     driver: awslogs
  #     options: 
  #       awslogs-group: madresearchden-test
  #       awslogs-region: eu-west-2
  #       awslogs-stream-prefix: bokeh-server