name: Docker Compose Actions Workflow
on:
  push:
    branches: 
      - wagtail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker-compose up -d
      - name: Test
        run: docker ps -a