name: Docker Compose Actions Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker-compose up -d && docker exec -t mrd_django pytest
      # - name: Test
      #   run: docker exec -t mrd_django pytest