name: Docker Compose Actions Workflow
on:
  push:
    branches: 
      - wagtail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Start
        run: docker-compose up -d
      - name: Django Tests
        run: docker-compose exec -T mrd_django pytest